### ISSUE TITLE
polling rate

### ISSUE THREAD

**Issue by DomKM** [lynaghk/cljx#46]
cljx is a great way to write portable code and I was wondering if there is a way to speed up compiling. I noticed that [the polling rate is set to 1000ms](https://github.com/lynaghk/cljx/blob/b92a9f0cb24a6ee56095996fc47121b6a9e361b7/src/leiningen/cljx.clj#L50). Worst case, it takes a whole second just to notice that a file was changed.

What do you think of making the polling rate configurable or dropping it to something much lower, like 50ms?

**Comment by cemerick** [comment]
I dropped it to 250ms. I worry about going any further negatively impacting people with very large projects.

Available in `[org.clojars.cemerick/cljx "0.6.0-SNAPSHOT"]` until the final 0.6.0 release is cut.
