### ISSUE TITLE
Catch up with latest ClojureScript

### ISSUE THREAD

**Issue by viesti** [lynaghk/cljx#65]
We should update piggieback dependency to 0.1.5 to support CLJS 0.0-2665. Now with CLJS 0.0-2665 it can happen that ```lein cljx once``` works but we'll get an error missing implementation of the new 2 arg ```-setup``` method from IJavaScriptEnv (https://github.com/clojure/clojurescript/wiki/Custom-REPLs#expectations) when running a repl with piggieback middleware.

**Comment by cemerick** [comment]
Yup, this'll happen with the next release. In the meantime, a project-local piggieback dependency will force the usage of its latest.

**Comment by cemerick** [comment]
There's a PR I want to get into the next release. But until then, you can use `[org.clojars.cemerick/cljx "0.5.1-SNAPSHOT"]` to avoid this problem.
