### ISSUE TITLE
Source directories from parent directories don't work

### ISSUE THREAD

**Issue by Deraen** [lynaghk/cljx#68]
Using :source-paths like ["../shared/src/cljx"] doesn't work.

```
Exception in thread "main" java.io.FileNotFoundException: 
/home/juho/Source/foobar/target/generated/clj/file:/home/juho/Source/foobar/app1/../shared/src/cljx/foobar/common/transit.clj (No such file or directory), compiling:(/tmp/form-init2327862490854915151.clj:1:72)
```

This would be fixed by #67

**Comment by cemerick** [comment]
I believe this is now fixed, though I would emphasize my comment @ https://github.com/lynaghk/cljx/pull/67#issuecomment-74259223. You really shouldn't be relying on this to work, use symlinks instead if you want to bring in resources from outside of a project directory.

**Comment by Deraen** [comment]
Thanks, I finally had time to test this and symlinks seem to be working fine.
