### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by okal** [lynaghk/cljx#73]
I'd like to make some server environment variables available to CLJS, through something like `environ`. Does cljx enable this sort of functionality?

**Comment by cemerick** [comment]
No. Depending on when you're compiling your ClojureScript, that's something you'll want to splice into your CLJS source via a macro, or make available in your JS runtime explicitly (e.g. always load something like `"window.__environment = {…}"` first, and refer to it in your ClojureScript via `js/window.__environment`).

**Comment by okal** [comment]
Thanks. Wound up using a macro.
