### ISSUE TITLE
Requiring unused dependency?

### ISSUE THREAD

**Issue by jacobemcken** [lynaghk/cljx#79]
I stumbled on a problem related to [requiring `leiningen.repl` in `cljx.plugin`][1] but it doesn't seem to be used?

I experienced the issue when updating from 0.4.0 to 0.5.0 or 0.6.0 in Immutant 1.1.4 where starting up the Immutant server would fail in bootstrap runtime, where lein-core is available, but leinignen itself isn't

Could `leiningen.repl` just be deleted?

[1]: https://github.com/lynaghk/cljx/blob/master/src/cljx/plugin.clj#L3

**Comment by cemerick** [comment]
Yeah, that could be removed, looks spurious. PR, please.

**Comment by jacobemcken** [comment]
Is it possible to get a new releasewhich includes this... I have some automatic tests which wont run because of this?  (a SNAPSHOT would do)

**Comment by cemerick** [comment]
turning on the @lynaghk bat-light here… :-)

**Comment by lynaghk** [comment]
Deployed `com/keminglabs/cljx/0.7.0-SNAPSHOT/cljx-0.7.0-20151201.172807-1.jar` to Clojars.
Hope this buys you some time @jacobemcken to migrate to cljc or your own fork of cljx, since I'mma take this bat-light away from Chas next time I see him =P

**Comment by jacobemcken** [comment]
hehe it will! Thanks alot!
